Feat/run model
EnnioEnnio/dl_facemask_detector pull request #19
Opened 2023-08-05 17:35 UTC by EnnioEnnio

closes #17

2023-08-05 17:55 UTC, Toalaah requested changes

2023-08-05 17:55 UTC, Toalaah commented on run_model.py
> +from torchvision.datasets import ImageFolder
```suggestion
```

unused imports

2023-08-05 17:55 UTC, Toalaah commented on run_model.py
> +from PIL import Image
```suggestion
```

unused import

2023-08-05 17:55 UTC, Toalaah commented on run_model.py
> +    parser.add_argument("--image", type=str, help="Path to the input image.")
```suggestion
    parser.add_argument("--image", type=str, help="Path to the input image.", required=True)
```

This provides a nicer error message rather than stacktrace when the user forgets to provide this flag

Before:
```
❯ MODEL=model.pt python3 run_model.py
[INFO] [run_model] Model path: /home/samuel/src/dl-project/code/model.pt
Traceback (most recent call last):
  File "/nix/store/5jm15bnjr7j3dh0c7jrn2k4m6r7n9d9f-python3-3.10.1-env/lib/python3.10/site-packages/PIL/Image.py", line 3240, in open
    fp.seek(0)
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samuel/src/dl-project/code/run_model.py", line 37, in <module>
    run_model(model, args.image)
  File "/home/samuel/src/dl-project/code/run_model.py", line 14, in run_model
    image = process_single_image(image_path)
  File "/home/samuel/src/dl-project/code/data_loader.py", line 117, in process_single_image
    image = Image.open(image_path)
  File "/nix/store/5jm15bnjr7j3dh0c7jrn2k4m6r7n9d9f-python3-3.10.1-env/lib/python3.10/site-packages/PIL/Image.py", line 3242, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'NoneType' object has no attribute 'read'
```
After:
```
❯ MODEL=model.pt python3 run_model.py
usage: run_model.py [-h] --image IMAGE
run_model.py: error: the following arguments are required: --image
```

2023-08-05 17:55 UTC, Toalaah commented on README.md
> +python run_model.py --image=path/to/image
Mega nitpick, feel free to reject: for the sake of consistency I would align the code snippet with the others

```suggestion
MODEL=$(pwd)/model.pt python3 run_model.py --image=path/to/image
```

2023-08-07 09:23 UTC, EnnioEnnio commented on README.md
> +python run_model.py --image=path/to/image
Consistency sounds nice - could you explain what that does? why do I run /model.pt  before and what is the pwd variable, where is it coming from?

2023-08-08 13:47 UTC, EnnioEnnio commented on README.md
> +python run_model.py --image=path/to/image
Thank's for the clarification!

2023-08-08 13:50 UTC, Toalaah approved these changes

2023-08-08 13:50 UTC, merged