add naive approach for resizing the images
EnnioEnnio/dl_facemask_detector pull request #3
Opened 2023-07-07 14:10 UTC by EnnioEnnio

Currently Images are stretched to fit 256x256 causing change in aspect ratio.
somehow rotation occurs sometimes which led me to the idea that our CNN should be able to detect that as well - what do you think?  

I read [here on cs.se](https://cs.stackexchange.com/questions/134628/how-does-cnn-deal-with-rotation-invariant-pictures) that a simple method would be to just rotate training images randomly and train for more epochs.

2023-07-09 08:35 UTC, Toalaah requested changes
Apologies for the delayed response, was busy that last couple of days. I think that rotation detection is definitely a nice feature to support!

WRT normalization of the image sizes, the only other thing that came to mind for me is possibly using 0-padding instead of resizing. That way features are not stretched / compressed, but TBH I am not entirely sure on whether this is even that much of an issue for the CNN. I think this is a fine approach for now.

Furthermore, I suppose that padding would require more training epochs as theree are more possible locations fot the actual image to be placed inside of the padded canvas (actually, a quick search shows results which suggest the [opposite](https://journalofbigdata.springeropen.com/articles/10.1186/s40537-019-0263-7) in certain conditions). Perhaps we could add processing options for both in the future, giving us something to compare against for the report? Would be happy to implement this in a future PR.

2023-07-09 08:35 UTC, Toalaah commented on data_loader.py
> +from PIL import Image
This is not part of the stdlib, no? I would add this to `requirements.txt`

2023-07-10 14:50 UTC, EnnioEnnio commented on data_loader.py
> +from PIL import Image
Ah funny, didn't know that - import just worked without adding it to my conda env.
Added it to `requirements.txt`, thanks for the hint!

2023-07-10 15:02 UTC, EnnioEnnio commented
Absolutely no worries, I also try to keep my weekends free from Uni :) 
Re rotation detection: Do you want rotation to be detected on input? I originally meant that it would be nice if it didn't matter for the recognition if the image is rotated or not. 


Re zero-padding: I initially wanted to simply add padding so as not to distort the images, but didn't have enough time to do so, hence "naive approach" in the title. In the next iteration then 😅. 
We could also try both and see if the performance improves, or degrades.

Regarding the position of the image I feel that this might not matter as they are sensitive to spacial relations but not the specific location of a feature (translational invariance) - but I might be wrong here.

2023-07-10 15:19 UTC, Toalaah commented
> I originally meant that it would be nice if it didn't matter for the recognition if the image is rotated or not.

This is also what I understood regarding rotation. Let us do it like this.
 
> We could also try both and see if the performance improves, or degrades.

Sounds good :+1:

2023-07-10 15:40 UTC, merged